### ISSUE TITLE
Linear Regression takes lot of time for vertical lines.

### ISSUE THREAD

**Issue by ameybhavsar24** [CodingTrain/website#1115]
*This is a issue regarding the **linear regression using tf.js***

A vertical line has a slope of infinity. It would take lots of time for tensor-flow to approximate variable 'm' at a really high number.
about:blank#blocked
Moreover, I have observed that more horizontal is the dataset the faster it approximates the mean line.
The reason for this basically is that a *horizontal line* has a smaller slope(m), whereas, as you move toward the vertical lines, the slope values increase very rapidly, hence approximating them becomes time-consuming.

Is there as workaround for this?
![bandicam20190215143230743](https://user-images.githubusercontent.com/28699912/52847256-b1f08800-3131-11e9-9f5a-23d5e3d2b53c.gif)

**Comment by Paladorn** [comment]
I don't know if it would help, but maybe it's a better idea to think a line as a angle and an offset. It's easy to transform that into a line (even vertical). And the advantage is that le slope of the line depends linearly on the angle (different from m that must increase a lot for vertical lines).
Maybe it could work much faster in that kind of cases

**Comment by ameybhavsar24** [comment]
> I don't know if it would help, but maybe it's a better idea to think a line as a angle and an offset. It's easy to transform that into a line (even vertical). And the advantage is that le slope of the line depends linearly on the angle (different from m that must increase a lot for vertical lines).
> Maybe it could work much faster in that kind of cases

**Comment by ameybhavsar24** [comment]
> I don't know if it would help, but maybe it's a better idea to think a line as a angle and an offset. It's easy to transform that into a line (even vertical). And the advantage is that le slope of the line depends linearly on the angle (different from m that must increase a lot for vertical lines).
> Maybe it could work much faster in that kind of cases
Yes, instead of X and Y coordinates, polar coordinates could be used. 
Can you give a idea about the model?

**Comment by Paladorn** [comment]
Yes, for the moment the model calculate the y coordinate based on the x one (y=m*x+b)
But if you find a relation (simple) between the radius and the angle theta(r), you should be able to use the radius as input. (for exemple, if your line go through the origin, it's a constant function.

But there is several problems:
- That relation is not linear if the line doesn't go through the origin, and it may be difficult to apply a simple method (There is probably tricks, like translating the points in order to make the line always go to the origin)
- Even when the line go to the origin, there is still an other problem: 
For one radius, we have 2 possibles outputs. (theta and theta+PI). That's because the origin is a point of symmetry. But we can handle that by accepting negative radius or by using a symmetry when we draw.

An other solution to keep using the precedent model. I don't know if it would work, but if you increase a lot the learning rate at the beginning, and reduce it over time, it may work.

**Comment by ameybhavsar24** [comment]
@Paladorn how about I create a translate function in the draw loop, with X and Y arguments.
**So in total, three inputs to the model, the angle(thetha), X and Y.** 
It will predict X and Y and then translate/rotate the line to minimise the loss.

Yes.
Also, there is a polar equation form of a straight line which takes the y-intercept in account. 

Read more here: http://www.nabla.hr/Z_MemoHU-015.htm

_This issue has been resolved._
