### ISSUE TITLE
Switching from CircleCI to GitHub Actions?

### ISSUE THREAD

**Issue by gruselhaus** [CodingTrain/website#1864]
@shiffman @vimkat @violetcraze What are your thoughts?

**Comment by violetcraze** [comment]
Since were hosting through GitHub it might make sense. I think the main advantage over circleci is a more automated workflow but we don't have to switch over the ci to take advantage of that. I know the coding train did some sponsored videos with circleci a while ago. @shiffman does that mean we've agreed you using their services? We could always add GitHub actions for a couple weeks and see if it makes more sense or just try out some of their features to start.

**Comment by vimkat** [comment]
I agree with @violetcraze! Let's try out GitHub Actions to start with and if we don't encounter any drastic issues, we could switch. 👍🏻

**Comment by shiffman** [comment]
There is no formal commitment to use CircleCI, happy to try GitHub actions!

**Comment by GypsyDangerous** [comment]
did #1868 fix this or is there more do?

**Comment by gruselhaus** [comment]
@violetcraze Should we change the required checks to GitHub Actions?

**Comment by violetcraze** [comment]
Yeah they seem to be working well I say go for it.

**Comment by gruselhaus** [comment]
https://github.community/t5/GitHub-Actions/Help-Weird-behavior-in-branch-protection-rule/m-p/37298#M2886

**Comment by gruselhaus** [comment]
Resolved.
