### ISSUE TITLE
File has no contents

### ISSUE THREAD

**Issue by jkr-wrk** [CodingTrain/website#3256]
https://github.com/CodingTrain/website/blob/main/learning/nature-of-code/5.3-flee-pursue-evade/evade/index.html

File should have the same contents as pursue/index.html

**Comment by gruselhaus** [comment]
@duskvirkus

**Comment by ArztKlein** [comment]
Looks like it has contents now, should the issue be closed?

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This issue seems resolved!

Sorry for the slow reply, we didn't really use the issues system on here recently.
We will move to a new website repo soon and would love your feedback on there!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

Hope to see you there!
