### ISSUE TITLE
Unit Testing and Continuous Integration

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#417]
Now that I have done some tutorials about unit testing and continuous integration, perhaps it would make sense to write some tests to make sure the jekyll build isn't broken and/or any markdown pages contain all the necessarily fields?

I know that @haideralipunjabi created #326 which may be relevant?

**Comment by nilsweb** [comment]
This sounds like a really good idea!
Unfortunately, I haven't worked with unit testing and CI yet (and also wasn't able to attend your last stream 😞) but that way I'll learn something as well.

**Comment by haideralipunjabi** [comment]
I haven't been in touch with your channel (coding in general) for the past few weeks. I will make sure to see the latest live stream. 
#326 shouldn't mess with Jekyll as it only modifies the README.md.

**Comment by nilsweb** [comment]
I've collected some ideas for test cases that should help verifying pull requests. We should check for:
- general Jekyll build errors
- valid URLs (to external sources, other videos, etc.)
- correct naming conventions (especially for the filename since it is used to build the URLs)
- missing properties (e. g. every contribution has to have an author and a URL; all videos have to have a date, title and number)
- use of `video_id` over a YouTube URL to enable automatic matching at a later point
- use of an internal URL (like `/CodingChallenges/...`) over `video_id` when the referenced video is already available on the website
- duplicated videos (could happen accidentally)

As soon as I notice something else that could be tested automatically, I'll update the list.

**Comment by arisanguinetti** [comment]
@nilsweb do you think you can convert your list to be checkboxes that can be thicked?

**Comment by shiffman** [comment]
Can this be closed with #471 and #501? New Issues can be opened for specific testing bugs and features?

**Comment by meiamsome** [comment]
I think I'd like to keep this open until more of the issues in @nilsweb's comment are resolved.

**Comment by haideralipunjabi** [comment]
I have zero experience with node, but hopefully I can contribute my ideas.
The valid url issue could be resolved by checking the status code each url returns, directly or using a service (if there is any?).
The naming convention could be achieved using RegEx.

**Comment by nilsweb** [comment]
I don't know if checking the status code for each URL is practical since there are a LOT of URLs to test. The tests would take a ridiculous amount of time to complete. Maybe we could use a RegEx here as well just to make sure that it *might* be a valid URL?

[Nils - Contact Using Hop](http://GetHop.com/?_hmid=1529180341)

On June 16, 2018 at 14:48 GMT, Haider Ali Punjabi <notifications@github.com> wrote:

I have zero experience with node, but hopefully I can contribute my ideas.
The valid url issue could be resolved by checking the status code each url returns, directly or using a service (if there is any?).
The naming convention could be achieved using RegEx.

**Comment by meiamsome** [comment]
I have a working test version for checking http statuses, but I'm not sure we actually want it to be an 'error' because we'll get people's PRs failing tests out of their own control. Perhaps it can just be printed to the logs so it can be checked manually? Not sure the best idea here, really, but implementing it let me find a bunch of broken links, so that's good.

As for correct naming conventions, can we define what that means, exactly? We already check the leading number so are we wanting to force lower-case kebab-case strings or is there more that should be checked?

**Comment by TheLastDestroyer** [comment]
can you add a line number to the format checker? If a line is blank the current output is less than helpful?

```
  ● _CodingChallenges › 130.1-fourier-transform-drawing.md › is formatted correctly

    Extra space at the end of line: '    '

      13 | const checkYAMLFormat = format => {
      14 |   if(format.match(/ \n/)) {
    > 15 |     throw new Error(`Extra space at the end of line: '${format.match(/[^\n]* \n/)[0].slice(0, -1)}'`);
      16 |   }
      17 |   if(format.match(/\n\n\n/)) {
      18 |     throw new Error('Double blank lines in YAML');
      
      at checkYAMLFormat (files.js:15:11)
      at YAMLFile.checkYAMLFormat [as load] (files.js:66:7)
      at Object.load (yaml.test.js:116:14)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 skipped, 2575 passed, 2582 total
Snapshots:   0 total
Time:        8.41s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
Exited with code 1
```
