### ISSUE TITLE
CC_93_DoublePendulum strange behavior

### ISSUE THREAD

**Issue by gldanoob** [CodingTrain/website#533]
### I tried to set the initializing values to:
```processing
float r1 = 200;
float r2 = 200;
float m1 = 40;
float m2 = 40;
float a1 = 1;
float a2 = 0;
float a1_v = 0;
float a2_v = 0;
float g = 1;
```
### At first the double pendulum doesn't carry much energy, so it swings low.
<img width="340" alt="low" src="https://user-images.githubusercontent.com/31832678/37864370-b08f8384-2fa8-11e8-9aae-e3368542cf63.PNG">

### However, later on it starts to swing higher and higher up:
<img width="417" alt="high" src="https://user-images.githubusercontent.com/31832678/37864388-dc3bbcfa-2fa8-11e8-9f0f-e43aedefa0da.PNG">
This is an abnormal behavior as energy won't increase itself. Is the code written wrongly or I'm thinking something wrong?

**Comment by Raymonzut** [comment]
Reproduced the issue:
![mad_pendulum](https://user-images.githubusercontent.com/40148684/74676221-cab4d300-51b5-11ea-9170-ddac779e5ec1.png)

Questioning if it has to do with the code. 

Floating-point imprecision is probably the reason.

Not an issue when you add the drag, as it outweighs the tiny impreciseness.

@gldanoob considered solved or closed?

**Comment by benjamw** [comment]
The issue seems to come from the fact that in the original webpage where the formulas were taken from, they begin by stating that:
```
x1 = L1 sin θ1
y1 = −L1 cos θ1   -- note the negative here
x2 = x1 + L2 sin θ2
y2 = y1 − L2 cos θ2   -- note the subtract here
```

This difference propagates through all the formulas, and is therefore different from what was entered in this script.

I tried entering in the proper value, but it was basically upside down. I then rotated the entire thing by PI, and it seemed to help, but it still blows up every once in a while. So there may be another factor that is causing the velocity to increase. Probably has something to do with the 
```
a1_v += a1_a;
a2_v += a2_a;
a1 += a1_v;
a2 += a2_v;
```
portion of the code. It seems like it needs some time values and derivatives.
