### ISSUE TITLE
website/_GuestTutorials/index.md is broken

### ISSUE THREAD

**Issue by WOLFI3654** [CodingTrain/website#655]
The links in the md file look broken

https://github.com/CodingTrain/website/blob/master/_GuestTutorials/index.md

**Comment by nilsweb** [comment]
Could you please clarify what exactly isn't working on your side? It looks all fine to me.

**Comment by WOLFI3654** [comment]
![codingtrain](https://user-images.githubusercontent.com/12684462/42947152-fcc58e40-8b6c-11e8-8758-9a7b8803950c.PNG)
I hope this screenshot clarifies the issue

**Comment by nilsweb** [comment]
Ah... That's what you've ment. Actually everything is alright here. You're looking at the file which is responsible for building the thecodingtrain.com website and GitHub can't resolve links built by Jekyll (the system behind the website). That's why it looks so weird. ;)
I'm closing this since everything should be clear now.
