### ISSUE TITLE
Ideas for the new CodinTrain Website

### ISSUE THREAD

**Issue by gruselhaus** [CodingTrain/website#806]
This issue is for collecting ideas for the new website.
If you have any Idea that improves the workflow or the UI share them with us!

@nilsweb @shiffman  is that okay for you?

## List: 
- [ ] https://github.com/CodingTrain/website/issues/806#issuecomment-431699621 (Button to jump back to the top)
- [x] https://github.com/CodingTrain/website/issues/806#issuecomment-433634517 (Enforce HTTPS)

**Comment by gruselhaus** [comment]
## Button to jump back to the top

 * Useful tool to "automatically scroll" back to the top https://github.com/tsuyoshiwada/sweet-scroll

![img_0231](https://user-images.githubusercontent.com/33380107/47271807-2731bf00-d57d-11e8-86f7-e529bbc73db4.jpg)

**Comment by gruselhaus** [comment]
#

**Comment by DonnyCraft1** [comment]
I notice that the website does not use https, that would be great implement!

**Comment by ShivanshuKantPrasad** [comment]
Why don't you host with GitHub. It does HTTPS automatically.

**Comment by gruselhaus** [comment]
> Why don't you host with GitHub. It does HTTPS automatically.

> I notice that the website does not use https, that would be great implement!

@DonnyCraft1  @ShivanshuKantPrasad Thank's for your Idea. 
For notice: this was discussed in an previous Issue. See #620

**Comment by gruselhaus** [comment]
Me too :)

**Comment by shiffman** [comment]
Ok, it's on now, let's see if anything breaks! Closing!

**Comment by shiffman** [comment]
Oops, this issue is not just about https. @gruselhaus as we come up with ideas we want to implement or discuss more specifically they should probably go into individual issue?

**Comment by gruselhaus** [comment]
@shiffman absolutely. Maybe we should create a new tag named "new Website"?

**Comment by gruselhaus** [comment]
Ok, i will close this issue now and create a new one for the open ideas. @nilsweb Would you be so kind and tag the new issues with a new tag?

**Comment by gruselhaus** [comment]
#826

**Comment by nilsweb** [comment]
Maybe instead of creating a new label and having ideas and/or discussions about the "new" system flying around in-between the other issues we could create a separate repository that holds those and later the future version? That way everything would be logically grouped together.
@shiffman Is it OK, if I do so?

**Comment by shiffman** [comment]
Sure!

**Comment by ShivanshuKantPrasad** [comment]
@nilsweb 
I think instead of creating a new repository it would be better to use the GitHub's Milestone or Project feature. That way things can still be grouped but it will remain connected to the main repo.
If a new repo is created there is a high chance that people would still add issues here instead of adding them to the new repo. It is evident by issues related to coding challenges that are present on this repo.
Having a single repo would avoid this problem.

**Comment by nilsweb** [comment]
I get your point @ShivanshuKantPrasad, thanks for sharing your concern but since this only affects issues/ideas for the new system, I think it would be better not to have them mixed together. 

Additionally, the future version of The Coding Train's website (at least most of it) won't use Jekyll anymore and would therefore be built "from scratch" with an entirely new codebase. And although I'm planning to have something running as soon as possible (after coming up with a somewhat decent plan of course) the "old" version still needs to be maintained in the meantime.
Even grouping issues with GitHub's projects or milestones could eventually "push back" the issues and/or pull requests for the old site which shouldn't happen.

I hope this makes sense to you. If you still think you might have a better idea on how to handle this the best way, feel free to drop a comment and let me know - a second point of view always helps a lot! 😄

**Comment by ShivanshuKantPrasad** [comment]
If you are re-implementing the site, then i think creating a new repo would be the best.

**Comment by nilsweb** [comment]
Does anyone have a good name suggestion? 🤔🙃

**Comment by ShivanshuKantPrasad** [comment]
I really like "thecodingtrai.in".
What technologies are going to be used?

**Comment by nilsweb** [comment]
Finally! Here it is: https://github.com/CodingTrain/project-trainsite :tada:
