### ISSUE TITLE
Courses / Tutorials

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#824]
Building off of the discussion in #367 and @nilsweb's work in #822, I wonder if the following hierarchy might make sense:

```
Coding Challenges
Beginners
    -> JavaScript with p5.js
    -> Java with Processing
    -> Machine Learning with ml5.js
Courses
    -> Topics in JavaScript
        -> Data
        -> Video
        -> ES6 etc.
    -> Intelligence and Learning
       -> Session 1...
       -> Session 2...
    -> Programming with Text
       -> Session 1...
       -> Session 2...
    -> Nature of Code
       -> Session 1...
       -> Session 2...
Streams 
```

**Comment by nilsweb** [comment]
Sounds logical to me!

I've just wondered if there's any difference between "Beginners" and "Courses" from a technical point of view? Maybe just being able to group certain courses together under a common name "like categories/tags/difficulty levels/etc." should be fine?

All in all, this would greatly simplify everything since we only have to worry about three main types of content. Any thoughts?

**Comment by shiffman** [comment]
A good question! The reason I separated out beginners is this is so frequently asked "Where do I start if I don't know anything?" -- so highlighting this on a top level feels worth it to me. But you are right, technically they are the same.

**Comment by Paladorn** [comment]
Why not creating in "Courses" 2 differents sections (or more) depending on the level of difficulty. 
It would be easier for beginners to start with the beginners tutorials and they will see what they will be able to do when they will know more about javascript and p5js

**Comment by shiffman** [comment]
Bumping this thread for a moment as I was looking at the recent work @gruselhaus completed in #1528. This also picks up on #357 

With YouTube Learning Playlists, I now have these "official" courses:

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6Zy51Q-x9tMWIv9cueOFTFA
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6YxDKpFzf_2D84p0cyk4T7X
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV

In theory the learning playlists make this website a little less necessary as they should help viewers find content, but I still think the organization here (not to mention the ability to submit community contributions) is worthwhile.

I personally would like to combine Courses / Tutorials into one thing, maybe just called "Learning" or "Courses"?

One quick fix we should do now is condense all the p5.js "tutorials" into one. The separate listings for 1.x, 2.x, etc. clutter the page and make scrolling down to see the workflow pages near impossible?

**Comment by gruselhaus** [comment]
Going to work on that now.

**Comment by nilsweb** [comment]
I think that's a good idea! Combining all tutorials in one course shouldn't be that hard. As soon as that's done I can go ahead and delete the collection from Jekyll so that everything stays (relatively) clean.

After everything has been moved, we might want to rethink how the videos/courses/etc. get presented on the website to keep them easy to find.
